# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence


stages:
  - test
  - build


".build_scripts":
  script:
    - rm -rf build  # Guarantee that tests and coverage are using latest src and tests
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - ./bin/test

build_win:
  rules:
    - if: $CI_COMMIT_TAG =~ /.*win.*/
      when: always
    - when: never
# Runs at 'build' stage
  stage: build
  tags:
    - "dtMath_CMake_tag_windows"
  extends: ".build_scripts"

# Job name 'build'
build_linux:
  rules:
    - if: $CI_COMMIT_TAG =~ /.*linux.*/
      when: always
    - when: never
# Runs at 'build' stage
  stage: build
  tags:
    # - dtMath_CMake_tag_windows
    - ros-noetic
  script:
    - apt update && DEBIAN_FRONTEND=noninteractive apt install -y git-core
  extends: ".build_scripts"


# Job name 'test'
test:
  # Runs at 'test' stage
  stage: test
  tags:
    # - dtMath_CMake_tag_windows
    - ros-noetic
  script:
    - ./bin/test



include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  services:
  tags:
    - cq-sans-dind

sast:
  stage: test


